/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'V506617' at '2/6/16 7:41 PM' with Gradle 2.9
 *
 * @author V506617, @date 2/6/16 7:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
