import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'V506617' at '2/6/16 7:41 PM' with Gradle 2.9
 *
 * @author V506617, @date 2/6/16 7:41 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
    @Test public void testMethod() 
    {
        System.out.println("Hello Hello Gradle");
        assertTrue(true);
    }
}
